* Three Titans of the Dessert                                                 :COOKIE:BROWNIE:ORIOS:

  - [ ] 1 cup unsalted butter, room temp
  - [ ] 1 cup granulated sugar
  - [ ] 3/4 cup brown sugar
  - [ ] 2 eggs
  - [ ] 1 tbsp vanilla extract
  - [ ] 2 1/2 cups flour
  - [ ] 1 tsp baking soda
  - [ ] 1 tsp salt
  - [ ] 2 cups chocolate chips
  - [ ] 1 package of oreo cookies
  - [ ] 1 package of brownie mix (to be prepared as directed on the
    box) I used Ghiradelli dulce de leche (totally optional, I threw
    it in because it was in my fridge and I figured this recipe
    could use a bit more sugar?!?)

  Preheat the oven to 350 and line a 9X13″ pan with parchment paper

  Cream the butter and both sugars (brown and granulated) until light
  and fluffy. Add eggs followed by vanilla and mix well.

  Add the flour, baking soda and salt and continue to beat until well
  combined. Fold in the chocolate chips. Press the cookie dough evenly
  into the pan.

  Now place the oreos on top of the cookie dough. Surprisingly enough,
  there are just enough oreos to top the whole thing! Dollop the dulce
  du leche on top of the oreos.

  Prepare brownie batter as directed (I didn’t even wash out my mixer
  bowl…just scrape the cookie dough clean and move on!). Pour brownie
  batter on top and smooth it around with a spatula.

  Bake for 40-50 minutes. They should look slightly under baked. The
  edges will likely puff up and dry out a bit but you can trim them
  off afterwards and still have way more than enough gooey chocolatey
  squares to go around! Some of the comments in this post suggest that
  40 minutes is too long to bake, so it’s recommended to start peeking
  in on them after about 30 minutes.
