* Eggs Benedict Bacon Potato Pie
* Irish Beef Savory Pie
  To make the pies, make the dough and shape into small pie
  tins. Strain meat, onions, and carrots into the pie and seal then
  bake until crust is golden brown (brush the pies with whisked egg
  yolk).

  Place in a deep plate and use the stew fluid to make a thick
  gravy. Quartered and roasted potatoes should be on the side and the
  gravy goes on-top.

  
** Dough
   - [ ] 2½ cups all-purpose flour
   - [ ] 1 teaspoon kosher salt
   - [ ] 1 cup (2 sticks) chilled unsalted butter, cut into pieces
   - [ ] 2 tablespoons apple cider vinegar

   Pulse flour and salt in a food processor to combine. Pulse in
   butter until mixture resembles coarse meal with pieces of butter
   still visible, about 20 pulses.
   
   Combine vinegar and ½ cup ice water in a measuring cup. Pulsing,
   drizzle in vinegar mixture; pulse until dough just holds together
   when squeezed (it should still be crumbly), about 10 pulses.
   
   Turn out dough and divide in half. Place each half on a sheet of
   plastic wrap and use plastic to press into disks. Wrap and chill
   until firm, about 2 hours.

** Irish Guinness Beef Stew
   - [ ] 1-2 tablespoons of rapeseed oil
   - [ ] 2 lbs shoulder of beef, cut into one inch chunks
   - [ ] 1 onion, chopped
   - [ ] 2 carrots, roughly chopped
   - [ ] 2 celery sticks, roughly chopped
   - [ ] 2 cloves garlic, finely sliced
   - [ ] 1 cup beef stock
   - [ ] 500ml of Guinness
   - [ ] Sea Salt and ground black pepper
   - [ ] 1 bay leaf
   - [ ] ¼ cup of plain flour

   Heat the oil in a large pot and brown the meat in two batches, be
   careful not to overcrowd the pan. Remove and set aside on a
   plate. Add another drop of oil if you need it and then fry off the
   onion, carrots and celery. Add the meat back into the pot along
   with the garlic.

   Pour in the stock, Guinness, one bay leaf and season to
   taste. Simmer gently for about 1 1/2 hours until the liquid has
   reduced. If the sauce isn’t thick enough strain the juices into a
   bowl and then transfer to a small sauce pan. Mix a little of the
   sauce with the flour over heat until you have a smooth paste, then
   whisk through the rest of the liquid. Simmer gently until you have
   a thickened sauce, then tip back over the meat. Serve with mashed
   potatoes or crusty bread.
