* Bacon wrapped Anaheim peppers                                :BACON:PEPPER:ANAHEIM:CHEESE:STUFFED:
  
  1. [ ] 4 medium Anaheim peppers
  2. [ ] 8 strips of Bacon
  3. [ ] Cream cheese
  4. [ ] Coconut flour
  5. [ ] Coconut flakes
  6. [ ] Mayonnaise
  7. [ ] Chipotle pepper powder
  8. [ ] Salt
  
  Mix the mayonnaise and chipotle powder until desired
  spiciness/smokiness is achieved.
  
  Pre-heat oven to 400° and place bacon on broiling pan, cook bacon
  till it's crispy but still malleable.
  
  - Cut the peppers at the top and fill with cream cheese.
  - Mix coconut flour salt and flakes then batter peppers lightly.
  - Pour bacon grease into a frying pan and turn to high.
  - Fry the battered peppers in the bacon grease until crispy (some
    cream cheese may leak out).
  - Wrap the fried peppers with the bacon.
  
  Dip the peppers in the mayo and chow down.

* Butter curry chicken with riced cauliflower              :INDIAN:BUTTER:CHICKEN:CURRY:CAULIFLOWER:
  
  1. [ ] 1-2 Tbsp of Ghee (clarified butter used in Indian dishes)
  2. [ ] Curry paste (bought or made)
  3. [ ] 1 Roasted Chicken
  4. [ ] 1 Cauliflower head
  5. [ ] 2 Cans of coconut milk
  6. [ ] 1 White onion
  7. [ ] 4 Carrots, whole
  8. [ ] Salt
  9. [ ] Bhut Jolokia
  
  Use a large and deep pan as if you make a lot, there will be a lot
  of liquid.
  
  - Heat up the ghee and put a dollop of curry paste in with it, stir
    till mixed then add a little bit of water (about 1/2 of a cup).
  - Chunk the onion and carrots and add to the mixture.
  - Add the pulled chicken to the mixture and simmer for 30 minutes,
    covered.
  - Snap off the florets of the cauliflower and put into a
    food-processor, pulsing it until chopped to a fine rice.
  - After 30 minutes of simmering the curry, add the coconut milk and
    simmer for another five minutes uncovered.
  - Add Bhut Jolokia (or any other pepper) and salt to taste.
  
  Place cauliflower at the bottom of a bowl and cover/drench with
  curry, you can also top the curry off with some chopped green onions
  or basil if desired.

* Tuna steak over spaghetti squash                                                     :TUNA:SQUASH:
  
  1. [ ] 1-2 Tuna steaks
  2. [ ] 1 Spaghetti squash
  3. [ ] 2 Tbsp of Coconut oil
  4. [ ] 1 Tbsp of Kerrygold Butter
  5. [ ] 3 Stalks of green onion
  6. [ ] Sweet vinegar (any will do, you can even use Bragg's ACV)
  7. [ ] Salt
  8. [ ] Pepper
  
  - Stab the squash twice and place in the microwave for 10
    minutes. It should be soft afterwards.
  - Heat up the butter in a deep pan and once the squash is finished
    nuking, take it out and split it, remove the seeds and scrape all
    of the spaghetti out into the pan of butter.
  - Cook on medium heat for a few minutes, stirring and flipping until
    the butter is absorbed by the spaghetti squash.
  
  Dole out the spaghetti squash onto the plates (about a cup each).
  
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Chop the green stalks of the onions, place the steaks on the bed of
  spaghetti squash, garnish with the green onions, drizzle (very
  lightly) the vinegar over the top!
* Tuna bacon morsels over cucumber                                 :TUNA:CUCUMBER:SOYSAUCE:SRIRACHA:
  
  1. [ ] 1 Tuna steak
  2. [ ] 1 Stalk of green onion
  3. [ ] Soy sauce
  4. [ ] Garlic olive oil
  5. [ ] Cock sauce
  
  Pre-heat oven to 370° and line a pan with tin-foil for the bacon.
  
  - Place bacon in tray and put in the oven until crispy (but
    flexible).
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Slice cucumber and place tuna morsels on cucumber. Drizzle olive
  oil, then soy sauce, then cock sauce over the morsels. Break bacon
  up into pinky finger sized pieces and place on-top of the morsels.
  
  Chop green onion, garnish, and enjoy!

* Eggs benedict over rosemary ham and bell pepper                       :EGGS:BENEDICT:ROSEMARY:HAM:

  1. [ ] 2 Eggs
  2. [ ] 2 Red bell peppers
  3. [ ] Rosemary ham / ham
  4. [ ] Hollondaise sauce
  5. [ ] Chives
  6. [ ] Salt
  7. [ ] Pepper
  
  This recipe does not include making of the Hollondaise sauce; I
  personally like to purchase mine at Trader Joes but making it from
  scratch is certainly doable (just find a good recipe!)

  You'll also need an egg poacher.

  Slice the peppers in half and clean the halves out, pick one that
  has the flattest sides as possible and pack each of them with the
  ham.

  Once the eggs are finish then lift onto the peppers, coat with
  sauce, and garnish using the chives.

  Salt to taste.
* Mac & Cheese                                                              :CAULIFLOWER:MAC:CHEESE:

  1.  [ ] 1 Cauliflower Head (cut into small florets)
  2.  [ ] 6 Slices Bacon, diced
  3.  [ ] 1 Cup Cheddar Cheese
  4.  [ ] 1 Cup Cream Cheese (bacon / basil cream cheese spread)
  5.  [ ] 1 Cup Mushrooms quartered
  6.  [ ] 1 Cup Asparagus diced
  7.  [ ] 8oz Heavy Whipping Cream
  8.  [ ] 1 Chicken Breast Smoked diced
  9.  [ ] 1tsp Dijon Mustard
  10. [ ] 2oz Goat Cheese, soft

  Smoke the chicken. I use the [[http://www.seriouseats.com/2010/07/wok-skills-101-indoor-smoking-how-to-smoke-in-a-wok.html][wok method]], which makes it possible to
  smoke chicken inside the house. You can do this step ahead of time,
  cut the chicken up and keep it in the fridge until you are ready to
  use. This is a time intensive step, if you want to do it, make sure
  you start early.

  Dice bacon, quarter mushroom and cut asparagus. In a large pan,
  begin cooking the bacon. Add the mushrooms and asparagus, cook until
  bacon is crispy (I like it half way rendered with still some fat in
  it) and mushrooms are soft but asparagus is still crisp.

  While the bacon is cooking, start processing the cauliflower. Cut it
  up into tiny florets. Remember, this is your pasta so cut it up to
  macaroni size. This step takes time.

  Bring large pot of water to boil, preheat oven to 375, add
  cauliflower to boiling water. Cook for 5 minutes until 'tender
  crisp' or aldente.

  In a sauce pan bring cream to a simmer and add mustard and cream
  cheese, wisk until incorporated. Add 1 cup of cheddar cheese and
  coat cheese, stir until melted, remove from heat.

  Drain the cauliflower, put out on dish towel to dry (or use a salad
  spinner). Put the cauliflower in a large baking dish.

  Add the chicken, bacon, mushrooms, asparagus. Cover with cheese
  sauce and mix. Add another cup of cheddar cheese to the top and
  top-off with pork rind crumbs.

  Bake for 15 minutes or until dish is bubbling and you have a nice
  crust on the top.

* Brownie Cookies                                                                    :COOKIE:BROWNY:

  1.  [ ] 1 Scoop Vanilla Protein Powder
  2.  [ ] 1/4 Cup Cocoa Powder
  3.  [ ] 1/4 Tsp Salt
  4.  [ ] 1/2 Tsp Baking Soda
  5.  [ ] 1 Tbsp Truvia
  6.  [ ] 1 Tsp Vanilla Extract
  7.  [ ] 1 Tsp Almond Extract
  8.  [ ] 1 Egg
  9.  [ ] 1 Cup Almond Butter (or real butter?)
  10. [ ] 1 Tbsp Walden Farms Chocolate Syrup
  
  Mix 1-4 first, mix 4-9 into that, then put 10 in last. Bake for 12
  minutes @ 350?
* Chorizo Chipotle Burgers                                                 :CHIPOTLE:BURGER:CHORIZO:

  1. [ ] 80/20 ground beef patties (grilled)
  2. [ ] Pork chorizo (sautéed on the stove)
  3. [ ] A couple thin slices of Boar's Head chipotle Gouda
  4. [ ] Baconnaise spread
  5. [ ] Raw onion
  6. [ ] A dollop of Wholly Guacamole
  7. [ ] A dollop of sour cream

* Cauliflower Rice Chilli                                                       :CHILLI:CAULIFLOWER:
  1. [ ] 1 Cauliflower
  2. [ ] 2lbs of grass-fed ground beef
  3. [ ] 1 Yellow onion
  4. [ ] 6 Slices of bacon
  5. [ ] Tomatoes
  6. [ ] Cumin
  7. [ ] Adobo Seasoning
  8. [ ] Garlic
  9. [ ] Chipotle pepper
  10. [ ] Salsa or Pico de Gallo
  11. [ ] Shredded cheese (or whatever cheese you want)
  12. [ ] Sour Cream

  Rice the cauliflower.

  Use butter to saute the onions, garlic, and cauliflower
  together.

  Brown the beef and strain excess fat. Place all chilli ingredients
  in a pot and bring to a roiling simmer, then simmer for 15-20
  minutes. Chilli shouldn't be too watery, once done cooking you may
  need to drain it a bit.

  Layer the cauliflower, garlic and onion mix on bottom of a casserole
  dish. Layer sourcream on top of that. Then layer the chilli on top
  of that with generous cheese over that.

  Bake till cheese is blackened in a few spots.

* Chicken Salad                                                                      :CHICKEN:SALAD:
  1. [ ] 4 Chicken Breasts
  2. [ ] 125g Celery
  3. [ ] 105 g Green peppers
  4. [ ] 20 g Green Onions
  5. [ ] ¾ Cup Sugar Free Sweet Relish
  6. [ ] ¾ Cup Mayo
  7. [ ] 3 Hardboiled Large Eggs


  - Preheat oven to 350 degrees and add chicken to an oven safe pan
    with a lid.
  - Add cream to cover chicken and cook for 45-60 minutes until
    chicken is done.
  - Put 3 eggs into a pan and cover with water, bring to a boil and
    cook for 15 minutes once boiling.
  - While chicken is cooking, chop up the peppers, onions and celery.
  - Let chicken cool and chop up.
  - Combine all ingredients into large prep bowl.
  - Chop up eggs and mix in. Do this last so the eggs don't get destroyed.
  - Distribute the mixture into 6 containers.
* Bacon Salad                                                                        :BACON:SALAD:
  1. [ ] 2 Packs of Happy Bacon
  2. [ ] 2 Handfulls of Cremini Mushrooms
  3. [ ] 1 Onion
  4. [ ] ½ Cup feta cheese


  - Stack bacon slices and "rip" them (with knife of course) down the
    middle.
    - Chop into pieces and cook in pan
    - Keep grease in pan but remove bacon
  - Sautee mushrooms and onions in bacon grease
  - Mix bacon, mushrooms, and onions together
  - Top with Feta
