* Chicken Divan Casserole                                    :CASSEROLE:CHEESE:CHICKEN:DINNER:LUNCH:
  - [ ] 2 boneless chicken breasts
  - [ ] 3 tbsp butter
  - [ ] 1 yellow onion
  - [ ] 3-4 cloves of chopped garlic
  - [ ] ½ tsp garlic salt
  - [ ] 1 cup chicken broth
  - [ ] 5 sprigs of finely chopped parsely
  - [ ] 1 head of cauliflower, riced
  - [ ] 1 cup heavy cream
  - [ ] 1 lemon juiced
  - [ ] ½ cup mayonnaise
  - [ ] 3 cups steamed broccoli
  - [ ] 2 cups shredded cheese

  *Cooking Instructions*
  1. Preheat the oven to 350°
  2. Fill a pot about halfway with water. Add both breasts of chicken
  3. Cook on high and bring to a boil until the chicken is cooked
     through (180°)
  4. Meanwhile, cook up the garlic and onions in a medium frying pan
     on a low heat with the ghee
  5. While that's cooking, blend up your cauliflower using a food
     processor or a good blender like a Ninja (or better). Do it for a
     couple seconds just until it looks like rice
  6. After about two minutes of the onions cooking, begin adding in
     the spices one at a time, mixing them into the onions as you go
  7. When the onions are soft, add the cauliflower
  8. When the cauliflower is soft, add the chicken broth. Cook,
     covered for about 10 minutes
  9. Check on your boiling chicken. Take it out and set it aside if
     it's reached 180°
  10. Add the cream and lemon juice and let simmer uncovered on low
      for about 10 minutes while it reduces. Mix it a few times
      throughout so it doesn't burn to the bottom
  11. Add mayo, mix, and turn off burner
  12. Begin pulling apart your chicken with a fork
  13. Add half your pulled chicken into the cauliflower cream mixture
  14. Use the other half to line the bottom of an 8x8 casserole dish
  15. On top of the chicken, layer in the steamed, chopped broccoli
  16. Top with the cauliflower cream mixture
  17. Top with cheddar cheese
  18. Put in the oven for 30 minutes, covered with tinfoil
  19. Remove tinfoil and cook 10 more minutes

  Enjoy!
     
* Fathead Pizza Crust                                                                 :PIZZA:DINNER:
  - [ ] 1½ cup shredded mozzarella cheese
  - [ ] ½ cup almond flour (the original called for ¾ but that turned
    out to be too much)
  - [ ] 1 egg
  - [ ] garlic salt or favoite seasoning

  Put mozzarella & cream cheese in a medium size microwaveable bowl
  and microwave for 1 minute, stir, then another 30 seconds and stir
  (if no microwave, heat up slowly on stove until very liquid).

  Stir in the egg and almond flour.

  Put dough down on parchment paper and use another sheet of parchment
  paper on-top to no-mess smooth the dough out (don't make it too thin
  though!)

  Dock (poke rows of holes) the flattened dough with a fork to prevent
  bubbling.

  Season and put it in a 425° oven.

  Check after 8 minutes and pop any bubbles that have developed.

  Continue baking for 12-15 minutes or until firm and tawny on-top.

  Then dress and top with whatever you want!
  
* Honey glazed cauliflower                                                 :CAULIFLOWER:HONEY:BACON:
  - [ ] 4 strips of slab bacon (savory bacon if you can)
  - [ ] 1/4 of an onion chopped
  - [ ] 2 cloves of garlic
  - [ ] 1 tbsp of garlic olive oil
  - [ ] 1 bowl of cauliflower florets
  - [ ] 1 tbsp of wild honey
  - [ ] 1 or 2 tsp of Harissa
  - [ ] 1 tsp of salt
  
  Makes two bowls.

  Cook the bacon in a cast-iron skillet. Start the pan cold and bring
  up to heat stopping in the middle of /low/ and /medium/.

  Once bacon is melt-in-your-mouth, move to another plate, chop it
  once it has cooled down.

  Then dump the cauliflower florets (should be about quarter sized)
  into the pan and stir up to make sure bacon greese is coating all of
  them. Turn the heat up to medium. Drizzle with a Garlic Olive Oil
  and stir once in a while.

  After about 3 minutes add coarsley chopped onions and pressed garlic
  to the cauliflower. Stir.

  After about 5 minutes or the cauliflower is nicely browned and
  soft-ish, add bacon bits to heat them back up and in 30 seconds
  plate the dish into bowls.

  Next, poor honey and harissa into a small dish with a few dribbles
  of water for lubrication and stir. Then portion this mixture out
  onto the cauliflower dishes and stir until lightly coated.

  NOTE: for next time, a fried egg on-top would probably be pretty
  badass.

* Bacon wrapped Anaheim peppers                                :BACON:PEPPER:ANAHEIM:CHEESE:STUFFED:
  - [ ] 4 medium Anaheim peppers
  - [ ] 8 strips of Bacon
  - [ ] Cream cheese
  - [ ] Coconut flour
  - [ ] Coconut flakes
  - [ ] Mayonnaise
  - [ ] Chipotle pepper powder
  - [ ] Salt
  
  Mix the mayonnaise and chipotle powder until desired
  spiciness/smokiness is achieved.
  
  Pre-heat oven to 400° and place bacon on broiling pan, cook bacon
  till it's crispy but still malleable.
  
  - Cut the peppers at the top and fill with cream cheese.
  - Mix coconut flour salt and flakes then batter peppers lightly.
  - Pour bacon grease into a frying pan and turn to high.
  - Fry the battered peppers in the bacon grease until crispy (some
    cream cheese may leak out).
  - Wrap the fried peppers with the bacon.
  
  Dip the peppers in the mayo and chow down.

* Butter curry chicken with riced cauliflower              :INDIAN:BUTTER:CHICKEN:CURRY:CAULIFLOWER:
  
  - [ ] 1-2 Tbsp of Ghee (clarified butter used in Indian dishes)
  - [ ] Curry paste (bought or made)
  - [ ] 1 Roasted Chicken
  - [ ] 1 Cauliflower head
  - [ ] 2 Cans of coconut milk
  - [ ] 1 White onion
  - [ ] 4 Carrots, whole
  - [ ] Salt
  - [ ] Bhut Jolokia
  
  Use a large and deep pan as if you make a lot, there will be a lot
  of liquid.
  
  - Heat up the ghee and put a dollop of curry paste in with it, stir
    till mixed then add a little bit of water (about 1/2 of a cup).
  - Chunk the onion and carrots and add to the mixture.
  - Add the pulled chicken to the mixture and simmer for 30 minutes,
    covered.
  - Snap off the florets of the cauliflower and put into a
    food-processor, pulsing it until chopped to a fine rice.
  - After 30 minutes of simmering the curry, add the coconut milk and
    simmer for another five minutes uncovered.
  - Add Bhut Jolokia (or any other pepper) and salt to taste.
  
  Place cauliflower at the bottom of a bowl and cover/drench with
  curry, you can also top the curry off with some chopped green onions
  or basil if desired.

* Tuna steak over spaghetti squash                                                     :TUNA:SQUASH:
  
  - [ ] 1-2 Tuna steaks
  - [ ] 1 Spaghetti squash
  - [ ] 2 Tbsp of Coconut oil
  - [ ] 1 Tbsp of Kerrygold Butter
  - [ ] 3 Stalks of green onion
  - [ ] Sweet vinegar (any will do, you can even use Bragg's ACV)
  - [ ] Salt
  - [ ] Pepper
  
  - Stab the squash twice and place in the microwave for 10
    minutes. It should be soft afterwards.
  - Heat up the butter in a deep pan and once the squash is finished
    nuking, take it out and split it, remove the seeds and scrape all
    of the spaghetti out into the pan of butter.
  - Cook on medium heat for a few minutes, stirring and flipping until
    the butter is absorbed by the spaghetti squash.
  
  Dole out the spaghetti squash onto the plates (about a cup each).
  
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Chop the green stalks of the onions, place the steaks on the bed of
  spaghetti squash, garnish with the green onions, drizzle (very
  lightly) the vinegar over the top!

* Tuna bacon morsels over cucumber                                 :TUNA:CUCUMBER:SOYSAUCE:SRIRACHA:
  
  - [ ] 1 Tuna steak
  - [ ] 1 Stalk of green onion
  - [ ] Soy sauce
  - [ ] Garlic olive oil
  - [ ] Cock sauce
  
  Pre-heat oven to 370° and line a pan with tin-foil for the bacon.
  
  - Place bacon in tray and put in the oven until crispy (but
    flexible).
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Slice cucumber and place tuna morsels on cucumber. Drizzle olive
  oil, then soy sauce, then cock sauce over the morsels. Break bacon
  up into pinky finger sized pieces and place on-top of the morsels.
  
  Chop green onion, garnish, and enjoy!

* Eggs benedict over rosemary ham and bell pepper                       :EGGS:BENEDICT:ROSEMARY:HAM:

  - [ ] 2 Eggs
  - [ ] 2 Red bell peppers
  - [ ] Rosemary ham / ham
  - [ ] Hollondaise sauce
  - [ ] Chives
  - [ ] Salt
  - [ ] Pepper
  
  This recipe does not include making of the Hollondaise sauce; I
  personally like to purchase mine at Trader Joes but making it from
  scratch is certainly doable (just find a good recipe!)

  You'll also need an egg poacher.

  Slice the peppers in half and clean the halves out, pick one that
  has the flattest sides as possible and pack each of them with the
  ham.

  Once the eggs are finish then lift onto the peppers, coat with
  sauce, and garnish using the chives.

  Salt to taste.

* Mac & Cheese                                                              :CAULIFLOWER:MAC:CHEESE:

  - [ ] 1 Cauliflower Head (cut into small florets)
  - [ ] 6 Slices Bacon, diced
  - [ ] 1 Cup Cheddar Cheese
  - [ ] 1 Cup Cream Cheese (bacon / basil cream cheese spread)
  - [ ] 1 Cup Mushrooms quartered
  - [ ] 1 Cup Asparagus diced
  - [ ] 8oz Heavy Whipping Cream
  - [ ] 1 Chicken Breast Smoked diced
  - [ ] 1tsp Dijon Mustard
  - [ ] 2oz Goat Cheese, soft

  Smoke the chicken. I use the [[http://www.seriouseats.com/2010/07/wok-skills-101-indoor-smoking-how-to-smoke-in-a-wok.html][wok method]], which makes it possible to
  smoke chicken inside the house. You can do this step ahead of time,
  cut the chicken up and keep it in the fridge until you are ready to
  use. This is a time intensive step, if you want to do it, make sure
  you start early.

  Dice bacon, quarter mushroom and cut asparagus. In a large pan,
  begin cooking the bacon. Add the mushrooms and asparagus, cook until
  bacon is crispy (I like it half way rendered with still some fat in
  it) and mushrooms are soft but asparagus is still crisp.

  While the bacon is cooking, start processing the cauliflower. Cut it
  up into tiny florets. Remember, this is your pasta so cut it up to
  macaroni size. This step takes time.

  Bring large pot of water to boil, preheat oven to 375, add
  cauliflower to boiling water. Cook for 5 minutes until 'tender
  crisp' or aldente.

  In a sauce pan bring cream to a simmer and add mustard and cream
  cheese, wisk until incorporated. Add 1 cup of cheddar cheese and
  coat cheese, stir until melted, remove from heat.

  Drain the cauliflower, put out on dish towel to dry (or use a salad
  spinner). Put the cauliflower in a large baking dish.

  Add the chicken, bacon, mushrooms, asparagus. Cover with cheese
  sauce and mix. Add another cup of cheddar cheese to the top and
  top-off with pork rind crumbs.

  Bake for 15 minutes or until dish is bubbling and you have a nice
  crust on the top.

* Brownie Cookies                                                                    :COOKIE:BROWNY:
  - [ ] 1 Scoop Vanilla Protein Powder
  - [ ] 1/4 Cup Cocoa Powder
  - [ ] 1/4 Tsp Salt
  - [ ] 1/2 Tsp Baking Soda
  - [ ] 1 Tbsp Truvia
  - [ ] 1 Tsp Vanilla Extract
  - [ ] 1 Tsp Almond Extract
  - [ ] 1 Egg
  - [ ] 1 Cup Almond Butter (or real butter?)
  - [ ] 1 Tbsp Walden Farms Chocolate Syrup
  
  Mix 1-4 first, mix 4-9 into that, then put 10 in last. Bake for 12
  minutes @ 350?

* Chorizo Chipotle Burgers                                                 :CHIPOTLE:BURGER:CHORIZO:
  - [ ] 80/20 ground beef patties (grilled)
  - [ ] Pork chorizo (sautéed on the stove)
  - [ ] A couple thin slices of Boar's Head chipotle Gouda
  - [ ] Baconnaise spread
  - [ ] Raw onion
  - [ ] A dollop of Wholly Guacamole
  - [ ] A dollop of sour cream

* Cauliflower Rice Chilli                                                       :CHILLI:CAULIFLOWER:
  - [ ] 1 Cauliflower
  - [ ] 2lbs of grass-fed ground beef
  - [ ] 1 Yellow onion
  - [ ] 6 Slices of bacon
  - [ ] Tomatoes
  - [ ] Cumin
  - [ ] Adobo Seasoning
  - [ ] Garlic
  - [ ] Chipotle pepper
  - [ ] Salsa or Pico de Gallo
  - [ ] Shredded cheese (or whatever cheese you want)
  - [ ] Sour Cream

  Rice the cauliflower.

  Use butter to saute the onions, garlic, and cauliflower
  together.

  Brown the beef and strain excess fat. Place all chilli ingredients
  in a pot and bring to a roiling simmer, then simmer for 15-20
  minutes. Chilli shouldn't be too watery, once done cooking you may
  need to drain it a bit.

  Layer the cauliflower, garlic and onion mix on bottom of a casserole
  dish. Layer sourcream on top of that. Then layer the chilli on top
  of that with generous cheese over that.

  Bake till cheese is blackened in a few spots.

* Chicken Salad                                                                      :CHICKEN:SALAD:
  - [ ] 4 Chicken Breasts
  - [ ] 125g Celery
  - [ ] 105 g Green peppers
  - [ ] 20 g Green Onions
  - [ ] ¾ Cup Sugar Free Sweet Relish
  - [ ] ¾ Cup Mayo
  - [ ] 3 Hardboiled Large Eggs


  - Preheat oven to 350° and add chicken to an oven safe pan
    with a lid.
  - Add cream to cover chicken and cook for 45-60 minutes until
    chicken is done.
  - Put 3 eggs into a pan and cover with water, bring to a boil and
    cook for 15 minutes once boiling.
  - While chicken is cooking, chop up the peppers, onions and celery.
  - Let chicken cool and chop up.
  - Combine all ingredients into large prep bowl.
  - Chop up eggs and mix in. Do this last so the eggs don't get destroyed.
  - Distribute the mixture into 6 containers.

* Bacon Salad                                                                        :BACON:SALAD:
  - [ ] 2 Packs of Happy Bacon
  - [ ] 2 Handfulls of Cremini Mushrooms
  - [ ] 1 Onion
  - [ ] ½ Cup feta cheese

  - Stack bacon slices and "rip" them (with knife of course) down the
    middle.
    - Chop into pieces and cook in pan
    - Keep grease in pan but remove bacon
  - Sautee mushrooms and onions in bacon grease
  - Mix bacon, mushrooms, and onions together
  - Top with Feta
