* Bacon wrapped Anaheim peppers :BACON:PEPPER:ANAHEIM:CHEESE:STUFFED:
  
  1. [ ] 4 medium Anaheim peppers
  2. [ ] 8 strips of Bacon
  3. [ ] Cream cheese
  4. [ ] Coconut flour
  5. [ ] Coconut flakes
  6. [ ] Mayonnaise
  7. [ ] Chipotle pepper powder
  8. [ ] Salt
  
  Mix the mayonnaise and chipotle powder until desired
  spiciness/smokiness is achieved.
  
  Pre-heat oven to 400° and place bacon on broiling pan, cook bacon
  till it's crispy but still malleable.
  
  - Cut the peppers at the top and fill with cream cheese.
  - Mix coconut flour salt and flakes then batter peppers lightly.
  - Pour bacon grease into a frying pan and turn to high.
  - Fry the battered peppers in the bacon grease until crispy (some
    cream cheese may leak out).
  - Wrap the fried peppers with the bacon.
  
  Dip the peppers in the mayo and chow down.

* Butter curry chicken with riced cauliflower :INDIAN:BUTTER:CHICKEN:CURRY:CAULIFLOWER:
  
  1. [ ] 1-2 Tbsp of Ghee (clarified butter used in Indian dishes)
  2. [ ] Curry paste (bought or made)
  3. [ ] 1 Roasted Chicken
  4. [ ] 1 Cauliflower head
  5. [ ] 2 Cans of coconut milk
  6. [ ] 1 White onion
  7. [ ] 4 Carrots, whole
  8. [ ] Salt
  9. [ ] Bhut Jolokia
  
  Use a large and deep pan as if you make a lot, there will be a lot
  of liquid.
  
  - Heat up the ghee and put a dollop of curry paste in with it, stir
    till mixed then add a little bit of water (about 1/2 of a cup).
  - Chunk the onion and carrots and add to the mixture.
  - Add the pulled chicken to the mixture and simmer for 30 minutes,
    covered.
  - Snap off the florets of the cauliflower and put into a
    food-processor, pulsing it until chopped to a fine rice.
  - After 30 minutes of simmering the curry, add the coconut milk and
    simmer for another five minutes uncovered.
  - Add Bhut Jolokia (or any other pepper) and salt to taste.
  
  Place cauliflower at the bottom of a bowl and cover/drench with
  curry, you can also top the curry off with some chopped green onions
  or basil if desired.

* Tuna steak over spaghetti squash :TUNA:SQUASH:
  
  1. [ ] 1-2 Tuna steaks
  2. [ ] 1 Spaghetti squash
  3. [ ] 2 Tbsp of Coconut oil
  4. [ ] 1 Tbsp of Kerrygold Butter
  5. [ ] 3 Stalks of green onion
  6. [ ] Sweet vinegar (any will do, you can even use Bragg's ACV)
  7. [ ] Salt
  8. [ ] Pepper
  
  - Stab the squash twice and place in the microwave for 10
    minutes. It should be soft afterwards.
  - Heat up the butter in a deep pan and once the squash is finished
    nuking, take it out and split it, remove the seeds and scrape all
    of the spaghetti out into the pan of butter.
  - Cook on medium heat for a few minutes, stirring and flipping until
    the butter is absorbed by the spaghetti squash.
  
  Dole out the spaghetti squash onto the plates (about a cup each).
  
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Chop the green stalks of the onions, place the steaks on the bed of
  spaghetti squash, garnish with the green onions, drizzle (very
  lightly) the vinegar over the top!
* Tuna bacon morsels over cucumber           :TUNA:CUCUMBER:SOYSAUCE:SRIRACHA:
  
  1. [ ] 1 Tuna steak
  2. [ ] 1 Stalk of green onion
  3. [ ] Soy sauce
  4. [ ] Garlic olive oil
  5. [ ] Cock sauce
  
  Pre-heat oven to 370° and line a pan with tin-foil for the bacon.
  
  - Place bacon in tray and put in the oven until crispy (but
    flexible).
  - Heat up the coconut oil in the same pan and crack a healthy amount
    of pepper and salt into the pan and put the tuna steak in.
  - Tuna steak should only be seared about a 1/4 of an inch through
    the top and bottom (mine usually takes about two minutes each
    side).
  
  Slice cucumber and place tuna morsels on cucumber. Drizzle olive
  oil, then soy sauce, then cock sauce over the morsels. Break bacon
  up into pinky finger sized pieces and place on-top of the morsels.
  
  Chop green onion, garnish, and enjoy!
