* Staples
** Eggs benedict over rosemary ham and bell pepper                      :EGGS:BENEDICT:ROSEMARY:HAM:
   1. [ ] 2 Eggs
   2. [ ] 2 Red bell peppers
   3. [ ] Rosemary ham / ham
   4. [ ] Hollondaise sauce
   5. [ ] Chives
   6. [ ] Salt
   7. [ ] Pepper
   
   This recipe does not include making of the Hollondaise sauce; I
   personally like to purchase mine at Trader Joes but making it from
   scratch is certainly doable (just find a good recipe!)

   You'll also need an egg poacher.

   Slice the peppers in half and clean the halves out, pick one that
   has the flattest sides as possible and pack each of them with the
   ham.

   Once the eggs are finish then lift onto the peppers, coat with
   sauce, and garnish using the chives.

   Salt to taste.

** Mac & Cheese                                                             :CAULIFLOWER:MAC:CHEESE:
   1.  [ ] 1 Cauliflower Head (cut into small florets)
   2.  [ ] 6 Slices Bacon, diced
   3.  [ ] 1 Cup Cheddar Cheese
   4.  [ ] 1 Cup Cream Cheese (bacon / basil cream cheese spread)
   5.  [ ] 1 Cup Mushrooms quartered
   6.  [ ] 1 Cup Asparagus diced
   7.  [ ] 8oz Heavy Whipping Cream
   8.  [ ] 1 Chicken Breast Smoked diced
   9.  [ ] 1tsp Dijon Mustard
   10. [ ] 2oz Goat Cheese, soft

   Smoke the chicken. I use the [[http://www.seriouseats.com/2010/07/wok-skills-101-indoor-smoking-how-to-smoke-in-a-wok.html][wok method]], which makes it possible to
   smoke chicken inside the house. You can do this step ahead of time,
   cut the chicken up and keep it in the fridge until you are ready to
   use. This is a time intensive step, if you want to do it, make sure
   you start early.

   Dice bacon, quarter mushroom and cut asparagus. In a large pan,
   begin cooking the bacon. Add the mushrooms and asparagus, cook until
   bacon is crispy (I like it half way rendered with still some fat in
   it) and mushrooms are soft but asparagus is still crisp.

   While the bacon is cooking, start processing the cauliflower. Cut it
   up into tiny florets. Remember, this is your pasta so cut it up to
   macaroni size. This step takes time.

   Bring large pot of water to boil, preheat oven to 375, add
   cauliflower to boiling water. Cook for 5 minutes until 'tender
   crisp' or aldente.

   In a sauce pan bring cream to a simmer and add mustard and cream
   cheese, wisk until incorporated. Add 1 cup of cheddar cheese and
   coat cheese, stir until melted, remove from heat.

   Drain the cauliflower, put out on dish towel to dry (or use a salad
   spinner). Put the cauliflower in a large baking dish.

   Add the chicken, bacon, mushrooms, asparagus. Cover with cheese
   sauce and mix. Add another cup of cheddar cheese to the top and
   top-off with pork rind crumbs.

   Bake for 15 minutes or until dish is bubbling and you have a nice
   crust on the top.


** Cauliflower Rice Chilli                                                      :CHILLI:CAULIFLOWER:
   1. [ ] 1 Cauliflower
   2. [ ] 2lbs of grass-fed ground beef
   3. [ ] 1 Yellow onion
   4. [ ] 6 Slices of bacon
   5. [ ] Tomatoes
   6. [ ] Cumin
   7. [ ] Adobo Seasoning
   8. [ ] Garlic
   9. [ ] Chipotle pepper
   10. [ ] Salsa or Pico de Gallo
   11. [ ] Shredded cheese (or whatever cheese you want)
   12. [ ] Sour Cream

   Rice the cauliflower.

   Use butter to saute the onions, garlic, and cauliflower
   together.

   Brown the beef and strain excess fat. Place all chilli ingredients
   in a pot and bring to a roiling simmer, then simmer for 15-20
   minutes. Chilli shouldn't be too watery, once done cooking you may
   need to drain it a bit.

   Layer the cauliflower, garlic and onion mix on bottom of a casserole
   dish. Layer sourcream on top of that. Then layer the chilli on top
   of that with generous cheese over that.

   Bake till cheese is blackened in a few spots.

** Chicken Salad                                                                     :CHICKEN:SALAD:
   1. [ ] 4 Chicken Breasts
   2. [ ] 125g Celery
   3. [ ] 105 g Green peppers
   4. [ ] 20 g Green Onions
   5. [ ] ¾ Cup Sugar Free Sweet Relish
   6. [ ] ¾ Cup Mayo
   7. [ ] 3 Hardboiled Large Eggs


   - Preheat oven to 350 degrees and add chicken to an oven safe pan
     with a lid.
   - Add cream to cover chicken and cook for 45-60 minutes until
     chicken is done.
   - Put 3 eggs into a pan and cover with water, bring to a boil and
     cook for 15 minutes once boiling.
   - While chicken is cooking, chop up the peppers, onions and celery.
   - Let chicken cool and chop up.
   - Combine all ingredients into large prep bowl.
   - Chop up eggs and mix in. Do this last so the eggs don't get destroyed.
   - Distribute the mixture into 6 containers.

** Chicken Cordon Bleu Casserole                                             :CHICKEN:CASSEROLE:HAM:
   :PROPERTIES:
   :SOURCE: http://cavemanketo.com/chicken-cordon-bleu-casserole/
   :END:
   1. [ ] 53 oz Chicken (breast or tender or thighs)
   2. [ ] 300 g Ham Steak
   3. [ ] 11 oz Jarlsberg Swiss Cheese
   4. [ ] 1 Cup Heavy Whipping Cream
   5. [ ] To Taste Salt, Pepper, Garlic Powder
   6. [ ] 1 cup Cream Cheese


   - Cut up chicken into 1" cubes, spread on bottom of pan.
   - Salt, pepper, garlic powder the chicken.
   - Cut up the ham into ½" cubes and sprinkle on top of chicken.
   - Shred Swiss cheese and spread over mixtures.
   - Heat the cream cheese in the microwave, then add the cream and mix, pour over casserole.
   - Mix the dish up.
   - Bake @ 350 degrees for 40 minutes.
   - Makes 10 portions. Half the recipe for 5 or a smaller pan.

** Bacon Cheddar Cauliflower Soup                                               :SOUP:BACON:CHEDDAR:
   :PROPERTIES:
   :SOURCE: http://cavemanketo.com/bacon-cheddar-cauliflower-soup/
   :END:
   1. [ ] 1 Cauliflower Head (1.016 kg)
   2. [ ] 2 Tbsp Olive Oil
   3. [ ] 1 Medium Onion (169 g)
   4. [ ] 4 Slices Bacon
   5. [ ] 12 Oz. Aged Cheddar
   6. [ ] 1 tsp Ground Thyme
   7. [ ] 3 Cups Chicken Broth
   8. [ ] ¼ Cup Heavy Cream
   9. [ ] 1 Oz Parmesan Cheese
   10. [ ] 1 Tbsp Minced Garlic


   - Dice up the cauliflower, place it on a foil lined sheet, and
     drizzle with olive oil.
   - Salt and pepper the cauliflower and bacon at 375 degrees for 35
     minutes.
   - Cook the bacon until crisp, ideally use a large pot that can fit
     the soup.
   - Dice a medium onion and fry it in the bacon grease.
   - Once the onion is done, add in the garlic and thyme and cook for
     30 seconds to a minute.
   - Add the Chicken Broth and cauliflower, then simmer covered for 20
     minutes.
   - While the cauliflower is simmering, shred some aged (ideally 3+
     years) cheddar.
   - Using an immersion blender, blend the cauliflower into a soup.
   - Add the cheese and blend more.
   - Add the bacon and cream and mix together with a spoon.

* Snacks
** Zucchini Parmesan Chips                                                   :SNACKS:CHIPS:ZUCCHINI:
   1. [ ] 2 medium zucchini (about 1 pound total)
   2. [ ] 1 tablespoon olive oil
   3. [ ] 1/4 cup freshly grated Parmesan (3/4-ounce)
   4. [ ] 1/8 teaspoon salt
   5. [ ] Freshly ground black pepper

   Preheat the oven to 450 degrees F. Coat a baking sheet with cooking
   spray.

   Slice the zucchini into 1/4-inch thick rounds. In a medium bowl,
   toss the zucchini with the oil. In a small bowl, combine the
   Parmesan, bread crumbs, salt, and a few turns of pepper. Dip each
   round into the Parmesan mixture, coating it evenly on both sides,
   pressing the coating on to stick, and place in a single layer on
   the prepared baking sheet.

   Bake the zucchini rounds until browned and crisp, 25 to 30
   minutes. Remove with spatula. Serve immediately.

** Spinach and Artichoke Dip                                             :SNACK:CHIPS:DIP:ARTICHOKE:
   :PROPERTIES:
   :SOURCE: http://cavemanketo.com/spinach-and-artichoke-dip/
   :END:
   1. [ ] 8 oz Cream Cheese
   2. [ ] ¼ Cup Mayo
   3. [ ] 4 oz Shredded Parmesan
   4. [ ] 1 Tbsp Minced Garlic
   5. [ ] 1 Tsp Crushed Basil
   6. [ ] 1 can Artichoke Hearts (14 oz)
   7. [ ] 255 g Spinach
   8. [ ] 8 oz Mozzarella Cheese
   9. [ ] To Taste Salt and pepper


   - Melt the cream cheese in the microwave.
   - Add the mayo and combine.
   - Add the shredded Parmesan, basil, garlic, salt and pepper.
   - Chop up the artichoke and add to the mix.
   - Thaw the spinach and combine with the other ingredients.
   - Grease an 8x8 dish and evenly spread the dip.
   - Cover the top of the dish with shredded mozzarella.
   - Bake at 350 for 30 minutes, then broil if the cheese is not done.

** Bacon Deviled Eggs                                                           :EGGS:DEVILED:BACON:
   :PROPERTIES:
   :SOURCE: http://cavemanketo.com/bacon-deviled-eggs/
   :END:
   1. [ ] 10 Large Eggs
   2. [ ] 5 Tbsp Mayo
   3. [ ] 4 Slices Thick Cut Bacon
   4. [ ] 2 Tbsp Sugar Free Pickle Relish
   5. [ ] To taste Paprika


   - Hard boil the eggs.
   - My method is to cover the eggs in cold water by an inch.
   - Apply high heat.
   - Once it starts boiling, start a 15 minute timer.
   - After 15 minutes, carefully pour out the hot water and cover the eggs with cold water.
   - Swap the water until the eggs are luke warm.
   - Crack the eggs all around, roll between your hands and peel.
   - Dry the peeled eggs.
   - Cut the eggs in half lengthwise and separate the yolks from the egg whites.
   - In a large bowl, crumble the yolks with a fork.
   - Add mayo until the mixture reaches a batter consistency.
   - Add the pickle relish and mix.
   - Add cooled, crumbled bacon.
   - Using a fork, fill the egg halves with the yolk mixture.
   - Sprinkle the deviled eggs with paprika.

* Desserts
** Adult Whipped Cream                                                       :WHIPPED:CREAM:ALCOHOL:
   1. [ ] 200 mL Heavy Cream
   2. [ ] ¼ tsp Vanilla
   3. [ ] Erythritol
   4. [ ] 50 mL Vanilla Vodka

   - Combine all ingredients and place in ISI Mini Easy Whip Container.
   - Charge with N2O cartridge.
   - Shake 3-4 times, if it comes out runny, shake more.
   - Serve on its own or on top of a drink or dessert.
